<!DOCTYPE html>
<html lang="sk">
	<head>
		<meta http-equiv="Content-Type" content="text/html charset=UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="Sablona">
		<meta name="author" content="">
		<title>TimeFly</title>
		<link href="./media/css/bootstrap.min.css" rel="stylesheet">
		<link href="./media/css/main.screen.css" rel="stylesheet">
		<link rel="stylesheet" href="./media/css/font-awesome.min.css">
		<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800,300' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href="./media/css/animate.css">
		
		<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script> -->
	</head>
	<body>
		<!-- Fixed navbar -->
		<nav class="navbar navbar-default navbar-fixed-top">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
						<i class="fa fa-bars" aria-hidden="true"></i>
					</button>
					<a class="navbar-brand page-scroll" href="index.php" title="TimeFly"><img src="media/img/Logo_Green.png" alt="Logo"></a>
					<div id="TeamName">Home/About us</div>
				</div>
				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
						<li class="current "><a class="page-scroll" onclick="ChangePage('#index');" href="#home" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" >Home</a></li>
						<li><a class="page-scroll" onclick="ChangePage('#index');" href="#about" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" >About us</a></li>
						<li><a onclick="ChangePage('#forum');"  data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">Blog</a></li>
						<li><a onclick="ChangePage('#tim');" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">Team</a></li>
					</ul>
				</div>
			</div>
		</nav>

		<div id="home" class="container slider under_nav">
			<div class="row">
				<div class="col-md-12 pln prn">
					<img src=media/img/slider.png alt="timefly">
				</div>
			</div>
		</div>